language: python
dist: precise
python:
- '3.5'
install: pip install -r requirements.txt
script: cms7 -e config/local.travis.yml
before_install:
- pip install --upgrade pip setuptools
- . $HOME/.nvm/nvm.sh
- nvm install 5.7.0
- nvm use 5.7.0
- npm install postcss-cli
- npm install svgo
- npm install
- openssl aes-256-cbc -K $encrypted_a6016b5c6ef3_key -iv $encrypted_a6016b5c6ef3_iv
  -in key1.enc -out key1 -d && chmod go-rwx deploy/key1 || true
-  openssl aes-256-cbc -K $encrypted_a6016b5c6ef3_key -iv $encrypted_a6016b5c6ef3_iv
  -in key2.enc -out key2 -d && chmod go-rwx deploy/key2 || true
after_success: ./deploy/deploy.sh
notifications:
  email: false
